"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Cards",
      [
        {
          question:
            "Кто сказал фразу: «Маг никогда не опаздывает, Фродо Беггинс, и никогда не приходит раньше; он всегда появляется тогда, когда положено»?",
          correctAnswer: "Гэндальф Серый",
          option1: "Гэндальф Белый",
          option2: "Гэндальф Серый",
          option3: "Саруман",
          option4: "Элронд",
          img: "https://cdni-vm.servicecdn.ru/2021.10/original/720_616d32dc82682c4d66f58f6e.jpg",
          topicId: 1,
        },
        {
          question: "Сколько Великих колец было дано расе людей?",
          correctAnswer: "9",
          option1: "3",
          option2: "7",
          option3: "9",
          option4: "1",
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWKS33vuCuN7nIgvn6FjkiAFGxCIVLrD_26g&s",
          topicId: 1,
        },
        {
          question: "Кого Арагорн призывает к камню Эреха?",
          correctAnswer: "Армию Мертвых",
          option1: "Хоббитов",
          option2: "Армию Мертвых",
          option3: "Армию Эльфов",
          option4: "Армию Орков",
          img: "https://cdnn21.img.ria.ru/images/15143/39/151433909_0:0:478:203_768x0_80_0_0_9b75c5d033b7591391650029508a5616.jpg",
          topicId: 1,
        },
        {
          question: "Кто в Амон Хен пытался отобрать кольцо у Фродо?",
          correctAnswer: "Боромир",
          option1: "Арагорн",
          option2: "Саурон",
          option3: "Смеагол",
          option4: "Боромир",
          img: "https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_65deeeea1759d95956e86446_65df05b6f9acc8146d1ec74d/scale_1200",
          topicId: 1,
        },
        {
          question: "Как нужно было уничтожить Кольцо Власти?",
          correctAnswer: "Бросить в вулкан",
          option1: "Бросить в вулкан",
          option2: "Выбросить в океан",
          option3: "Сжешь",
          option4: "Разрубить мечом",
          img: "https://img5tv.cdnvideo.ru/webp/shared/files/202104/1_1299126.jpg",
          topicId: 1,
        },
        {
          question: "Как называли камень, который охранял дракон в Хоббите?",
          correctAnswer: "Аркенстоун",
          option1: "Аметист",
          option2: "Алмаз",
          option3: "Аркенстоун",
          option4: "Агат",
          img: "https://avatars.dzeninfra.ru/get-zen_doc/271828/pub_653a10e17bed36510b0c5424_6564baa24ec66352011feabd/scale_1200",
          topicId: 2,
        },
        {
          question: "Как звали дракона из Хоббита?",
          correctAnswer: "Смауг",
          option1: "Исильдур",
          option2: "Галадриэль",
          option3: "Берримор",
          option4: "Смауг",
          img: "https://hagee.ru/uploads/posts/2024-05/43a7d0afb5_1111.webp",
          topicId: 2,
        },
        {
          question: "Как зовут главного героя фильма Хоббит?",
          correctAnswer: "Бильбо Бэггинс",
          option1: "Фродо Бэггинс",
          option2: "Бильбо Бэггинс",
          option3: "Перегрин Тук",
          option4: "Мериадок Брендибак",
          img: "https://fotoblik.ru/wp-content/uploads/2023/09/bilbo-beggins-12.webp",
          topicId: 2,
        },
        {
          question:
            "Как зовут эльфийского персонажа со светлыми волосами и голубыми глазами, который был метким лучником с утонченной внешностью?",
          correctAnswer: "Леголас",
          option1: "Филли",
          option2: "Килли",
          option3: "Леголас",
          option4: "Клоин",
          img: "https://avatars.dzeninfra.ru/get-zen_doc/1918821/pub_601553a67fd0a5390ff9a573_60155876d3c91450c6797d28/scale_1200",
          topicId: 2,
        },
        {
          question: "Как зовут существо, которое любило кольцо больше жизни?",
          correctAnswer: "Голлум",
          option1: "Голлум",
          option2: "Пиппин",
          option3: "Мэри",
          option4: "Гимли",
          img: "https://static.wikia.nocookie.net/villains/images/a/a3/GollumAUJTextlessPoster.jpeg/revision/latest?cb=20151020122542",
          topicId: 2,
        },
        {
          question: "Какой самый большой океан на Земле?",
          correctAnswer: "Тихий океан",
          option1: "Атлантический океан",
          option2: "Индийский океан",
          option3: "Северный Ледовитый океан",
          option4: "Тихий океан",
          img: "https://s0.rbk.ru/v6_top_pics/resized/640xH/media/img/0/85/756406436422850.jpg",
          topicId: 3,
        },
        {
          question: "Какая самая длинная река в мире?",
          correctAnswer: "Амазонка",
          option1: "Амазонка",
          option2: "Нил",
          option3: "Янцзы",
          option4: "Миссисипи",
          img: "https://snegir.org/upload/iblock/c57/rczkcjr5e7vvacu2ope2xo1v131dw0ab.jpg",
          topicId: 3,
        },
        {
          question: "Какая пустыня является самой большой в мире?",
          correctAnswer: "Сахара",
          option1: "Калахари",
          option2: "Гоби",
          option3: "Сахара",
          option4: "Аравийская",
          img: "https://s9.travelask.ru/uploads/post/000/005/876/main_image/full-a04f69d2e8e7a0364ea5805bb21a9117.jpg",
          topicId: 3,
        },
        {
          question: "Какой водопад является самым высоким в мире?",
          correctAnswer: "Анхель",
          option1: "Ниагарский водопад",
          option2: "Анхель",
          option3: "Виктория",
          option4: "Игуасу",
          img: "https://lifeglobe.net/x/entry/1072/angelwaterfall_3.jpg",
          topicId: 3,
        },
        {
          question: "Какой остров является самым большим в мире?",
          correctAnswer: "Гренландия",
          option1: "Мадагаскар",
          option2: "Борнео",
          option3: "Великобритания",
          option4: "Гренландия",
          img: "http://dvmarin.ru/wp-content/uploads/Pelis-700x463.jpg",
          topicId: 3,
        },
        {
          question: "В каком году началась Первая мировая война?",
          correctAnswer: "1914",
          option1: "1917",
          option2: "1914",
          option3: "1912",
          option4: "1918",
          img: "http://dosaaf34.ru/upload/medialibrary/e28/e284f770957ade5b97e7d95e74082b5f.jpg",
          topicId: 4,
        },
        {
          question: "Кто был первым русским царем?",
          correctAnswer: "Иван Грозный",
          option1: "Петр I",
          option2: "Иван Грозный",
          option3: "Александр I",
          option4: "Иван III",
          img: "https://avatars.dzeninfra.ru/get-zen_doc/1678002/pub_60223e38390eb32b9bd36855_602241d7390eb32b9bdafe08/scale_1200",
          topicId: 4,
        },
        {
          question: "В каком году произошло крещение Руси?",
          correctAnswer: "988",
          option1: "1054",
          option2: "1240",
          option3: "862",
          option4: "988",
          img: "https://tatmitropolia.ru/www/news2016/7/kreshhenie_595.jpg",
          topicId: 4,
        },
        {
          question: "Кто возглавил Октябрьскую революцию 1917 года?",
          correctAnswer: "Владимир Ленин",
          option1: "Лев Троцкий",
          option2: "Николай II",
          option3: "Иосиф Сталин",
          option4: "Владимир Ленин",
          img: "https://арюб.рф/www/%D0%B0/%D0%B0%D1%80%D1%8E%D0%B1.%D1%80%D1%84/images/articles_blocks/84717.jpg",
          topicId: 4,
        },
        {
          question: "В каком году распался Советский Союз?",
          correctAnswer: "1991",
          option1: "1990",
          option2: "1992",
          option3: "1989",
          option4: "1991",
          img: "https://okleyka.pro/upload/resize_cache/iblock/edb/490_490_0/krasnyi-gerb-flag-gerb-sssr-flag-sssr-serp-i-molot-sssr.jpg",
          topicId: 4,
        },
        {
          question: "Кто написал роман 'Преступление и наказание'?",
          correctAnswer: "Федор Достоевский",
          option1: "Лев Толстой",
          option2: "Иван Тургенев",
          option3: "Александр Пушкин",
          option4: "Федор Достоевский",
          img: "https://cdn.azbooka.ru/au/370x559/37562a16-8572-4e46-9f90-0eae9effd975.jpg",
          topicId: 5,
        },
        {
          question: " Кто является автором пьесы 'Горе от ума'?",
          correctAnswer: "Александр Грибоедов",
          option1: "Лев Толстой",
          option2: "Николай Гоголь",
          option3: "Александр Грибоедов",
          option4: "Михаил Лермонтов",
          img: "http://www.pravoslavie.ru/sas/image/102547/254765.p.jpg?2217504",
          topicId: 5,
        },
        {
          question: "Какой жанр произведения 'Война и мир' Льва Толстого?",
          correctAnswer: "Роман-эпопея",
          option1: "Поэма",
          option2: "Повесть",
          option3: "Роман-эпопея",
          option4: "Рассказ",
          img: "https://www.mann-ivanov-ferber.ru/assets/images/covers/33/31833/1.50x-thumb.png",
          topicId: 5,
        },
        {
          question: "Кто написал стихотворение 'Я помню чудное мгновенье'?",
          correctAnswer: "Александр Пушкин",
          option1: "Михаил Лермонтов",
          option2: "Сергей Есенин",
          option3: "Николай Некрасов",
          option4: "Александр Пушкин",
          img: "https://topdialog.ru/wp-content/uploads/2019/06/2rahp-e1560859340534-650x434.jpg",
          topicId: 5,
        },
        {
          question: "Как звали главного героя романа 'Герой нашего времени'?",
          correctAnswer: "Григорий Печорин",
          option1: "Павел Чичиков",
          option2: "Александр Чацкий",
          option3: "Евгений Онегин",
          option4: "Григорий Печорин",
          img: "https://avatars.dzeninfra.ru/get-zen_doc/1708007/pub_6033e841084cc34524d23387_6033eef4a332dd73734f7f26/scale_1200",
          topicId: 5,
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Cards", null, {});
  },
};
